version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Mount the named volume to MongoDB's data directory

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Mount the named volume to Redis's data directory

volumes:
  mongo_data:
    driver: local # Specifies a local volume driver
  redis_data:
    driver: local # Specifies a local volume driver
